var producer = {
    statstr1: `
{ "name": "rdkafka#producer-0", "type": "producer", "ts":1454476122172462, "time":1454476122, "replyq":0, "msg_cnt":0, "msg_max":500000, "brokers":{ "localhost:9092/bootstrap": { "name":"localhost:9092/bootstrap", "nodeid":-1, "state":"UP", "stateage":5989494, "outbuf_cnt":0, "outbuf_msg_cnt":0, "waitresp_cnt":0, "waitresp_msg_cnt":0, "tx":1, "txbytes":25, "txerrs":0, "txretries":0, "req_timeouts":0, "rx":1, "rxbytes":5747, "rxerrs":0, "rxcorriderrs":0, "rxpartial":0, "rtt": { "min":0, "max":0, "avg":0, "sum":0, "cnt":0 }, "toppars":{ } } , "10.0.1.3:9092/0": { "name":"10.0.1.3:9092/0", "nodeid":0, "state":"UP", "stateage":5982977, "outbuf_cnt":0, "outbuf_msg_cnt":0, "waitresp_cnt":0, "waitresp_msg_cnt":0, "tx":4, "txbytes":239, "txerrs":0, "txretries":0, "req_timeouts":0, "rx":4, "rxbytes":5906, "rxerrs":0, "rxcorriderrs":0, "rxpartial":0, "rtt": { "min":879, "max":879, "avg":879, "sum":879, "cnt":1 }, "toppars":{ "testtopic": { "topic":"testtopic", "partition":0} } } }, "topics":{ "testtopic": { "topic":"testtopic", "metadata_age":3964, "partitions":{ "0": { "partition":0, "leader":0, "desired":false, "unknown":false, "msgq_cnt":0, "msgq_bytes":0, "xmit_msgq_cnt":0, "xmit_msgq_bytes":0, "fetchq_cnt":0, "fetchq_size":0, "fetch_state":"none", "query_offset":0, "next_offset":0, "app_offset":0, "stored_offset":-1, "commited_offset":-1, "committed_offset":-1, "eof_offset":-1, "lo_offset":-1, "hi_offset":-1, "consumer_lag":-1, "txmsgs":2, "txbytes":70, "msgs": 2 } , "-1": { "partition":-1, "leader":-1, "desired":false, "unknown":false, "msgq_cnt":0, "msgq_bytes":0, "xmit_msgq_cnt":0, "xmit_msgq_bytes":0, "fetchq_cnt":0, "fetchq_size":0, "fetch_state":"none", "query_offset":0, "next_offset":0, "app_offset":0, "stored_offset":-1, "commited_offset":-1, "committed_offset":-1, "eof_offset":-1, "lo_offset":-1, "hi_offset":-1, "consumer_lag":-1, "txmsgs":0, "txbytes":0, "msgs": 1 } } } } }
`,
    drstr1: `
[ { "errcode": -192, "count": 2, "errstr": "Local: Message timed out" } ]
`,
};

var consumer = {
    statstr1: `
{ "name": "rdkafka#consumer-1", "type": "consumer", "ts":1454482265090874, "time":1454482265, "replyq":0, "msg_cnt":0, "msg_max":100000, "brokers":{ "localhost:9092/bootstrap": { "name":"localhost:9092/bootstrap", "nodeid":-1, "state":"UP", "stateage":24987927, "outbuf_cnt":0, "outbuf_msg_cnt":0, "waitresp_cnt":0, "waitresp_msg_cnt":0, "tx":4, "txbytes":112, "txerrs":0, "txretries":0, "req_timeouts":0, "rx":4, "rxbytes":623, "rxerrs":0, "rxcorriderrs":0, "rxpartial":0, "rtt": { "min":711, "max":711, "avg":711, "sum":711, "cnt":1 }, "toppars":{ } } , "10.0.1.3:9092/0": { "name":"10.0.1.3:9092/0", "nodeid":0, "state":"UP", "stateage":24980488, "outbuf_cnt":0, "outbuf_msg_cnt":0, "waitresp_cnt":1, "waitresp_msg_cnt":0, "tx":207, "txbytes":19879, "txerrs":0, "txretries":0, "req_timeouts":0, "rx":206, "rxbytes":15032, "rxerrs":0, "rxcorriderrs":0, "rxpartial":0, "rtt": { "min":385, "max":105813, "avg":86908, "sum":3476357, "cnt":40 }, "toppars":{ "testtopic": { "topic":"testtopic", "partition":1} , "testtopic": { "topic":"testtopic", "partition":0} } } }, "topics":{ "testtopic": { "topic":"testtopic", "metadata_age":4782, "partitions":{ "0": { "partition":0, "leader":0, "desired":true, "unknown":false, "msgq_cnt":0, "msgq_bytes":0, "xmit_msgq_cnt":0, "xmit_msgq_bytes":0, "fetchq_cnt":20, "fetchq_size":70, "fetch_state":"active", "query_offset":0, "next_offset":27, "app_offset":0, "stored_offset":-1, "commited_offset":-1, "committed_offset":-1, "eof_offset":27, "lo_offset":0, "hi_offset":26, "consumer_lag":0, "txmsgs":0, "txbytes":0, "msgs": 27 } , "1": { "partition":1, "leader":0, "desired":true, "unknown":false, "msgq_cnt":0, "msgq_bytes":0, "xmit_msgq_cnt":0, "xmit_msgq_bytes":0, "fetchq_cnt":20, "fetchq_size":70, "fetch_state":"active", "query_offset":0, "next_offset":30, "app_offset":0, "stored_offset":-1, "commited_offset":-1, "committed_offset":-1, "eof_offset":30, "lo_offset":0, "hi_offset":29, "consumer_lag":0, "txmsgs":0, "txbytes":0, "msgs": 30 } , "-1": { "partition":-1, "leader":-1, "desired":false, "unknown":false, "msgq_cnt":0, "msgq_bytes":0, "xmit_msgq_cnt":0, "xmit_msgq_bytes":0, "fetchq_cnt":0, "fetchq_size":0, "fetch_state":"none", "query_offset":0, "next_offset":0, "app_offset":0, "stored_offset":-1, "commited_offset":-1, "committed_offset":-1, "eof_offset":-1, "lo_offset":-1, "hi_offset":-1, "consumer_lag":-1, "txmsgs":0, "txbytes":0, "msgs": 0 } } } } }
`,
}


module.exports = {
    producer: producer,
    consumer: consumer,
}
